# version:  '3.0'
services:

  mysql:
    image: mysql
    volumes:
      # - /etc/localtime:/etc/localtime:ro
      - ./data/mysql:/var/lib/mysql:rw
      - ./logs/mysql:/var/lib/mysql-logs:rw
      # - ./dockerfiles/mysql/conf.d:/etc/mysql/conf.d:ro
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        # MYSQL_DATABASE: lottery_api_sale
        # MYSQL_USER: zhaojun
        # MYSQL_PASSWORD: zhaojun
    ports:
      - 3306:3306
    # deploy:
    #   restart_policy:
    #     condition: any

  adminer:
    image: adminer
    restart: always
    ports:
      - 6600:8080

  # redis-db:
  #   image: redis
  #   volumes:
  #     - ./data/redis/data:/data
  #     # - /etc/localtime:/etc/localtime:ro
  #   # deploy:
  #   #   restart_policy:
  #   #     condition: any
  #   ports:
  #     - 6379:6379

  # mongo:
  #   image: mongo
  #   restart: always
  #   volumes:
  #     # - /etc/localtime:/etc/localtime:ro
  #     - ./data/mongodb/data:/data/db:rw
  #     - ./data/mongodb/backup:/data/backup:rw
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: 123456
  #   ports:
  #     - 27017:27017


  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 7700:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
  #     ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017/


  # https://zhuanlan.zhihu.com/p/554864824
  # dolphindb:
  #   image: dolphindb/dolphindb-arm64:v3.00.0
  #   restart: always
  #   volumes:
  #     # - /etc/localtime:/etc/localtime:ro
  #     - ./data/dolphindb/etc:/dolphindb/etc:rw
  #     - ./data/dolphindb/data:/data/ddb/server/data:rw
  #   ports:
  #     - 8848:8848

  # postgres:
  #   container_name: postgres_container
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
  #     PGDATA: /data/postgres
  #   volumes:
  #      - ./data/postgres:/data/postgres
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - mynetwork
  #   restart: unless-stopped
  
  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #      - ./data/pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - mynetwork
  #   restart: unless-stopped

  tdengine:
    image: tdengine/tdengine:latest
    restart: always
    volumes:
      - ./data/tdengine:/var/lib/taos:rw
      - ./logs/tdengine:/var/log/taos:rw
    ports:
      - 6030:6030
      - 6041:6041
      - 6043-6060:6043-6060
      - 6043-6060:6043-6060/udp
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

